## Load data

In [1]:
import numpy as np
import pandas as pd

from scripts.task1_get_contexts import get_contexts, chain2bin

In [2]:
VERIFIED_TEXTS = '/media/yaugear/BackupData1/tatcorp/corpus/verified_texts_2017-09-24'
ALL_TEXTS = '/media/yaugear/BackupData1/tatcorp/corpus/tatcorp_dump_texts_2017-09-24'

In [3]:
all_sentences = get_contexts(VERIFIED_TEXTS, [])
achs = [chain2bin(word[1]) for sentence in all_sentences for word in sentence if word[1]]
all_chains = set([tuple(chain) for chain in achs])
len(all_chains)

1378

In [4]:
sentences1 = get_contexts(VERIFIED_TEXTS, [u'әле'])
len(sentences1)

80

In [5]:
sentences2 = get_contexts(VERIFIED_TEXTS, [u'ук'])
len(sentences2)

306

In [6]:
sentences3 = get_contexts(VERIFIED_TEXTS, [u'соң'])
len(sentences3)

69

In [7]:
def get_disamed_indexes(contexts):
    result = []
    chains = []
    for context in contexts:
        morph = context[2][1]
        if morph not in chains:
            chains.append(morph)
        result.append(chains.index(morph))
    return result, chains

In [120]:
true_indexes1, chains1 = get_disamed_indexes(sentences1)
print(chains1)
print(true_indexes1)

[u'\u04d9\u043b\u0435+PART', u'\u04d9\u043b\u0435+CNJ']
[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [9]:
true_indexes2, chains2 = get_disamed_indexes(sentences2)
print(chains2)
print(true_indexes2)

[u'\u0443\u043a+PART']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [211]:
chains2.append(u'ук+N+Sg+Nom')

In [10]:
true_indexes3, chains3 = get_disamed_indexes(sentences3)
print(chains3)
print(true_indexes3)

[u'\u0441\u043e\u04a3+POST', u'\u0441\u043e\u04a3+PART']
[0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [76]:
chains3.append(u'соң+Adv')

In [79]:
print(chain2bin(u'ук+N+Sg+Nom'))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [145]:
def printc(context):
    result = u''
    for row in context:
        if len(row) == 2:
            result += " %s(%s)" % row
    return result

In [146]:
print(printc(sentences1[0]))

 проблемасы(проблема+N+Sg+POSS_3(СЫ)+Nom;) хаман(хаман+Adv;) әле(әле+PART) кискен(кискен+Adj;) булып(бул+V+ADVV_ACC(Ып);)

In [147]:
def save_as(filename, contexts, labels):
    cons = []
    cons = [printc(context) for context in contexts]
    result = '\n'.join(['%s\t%s' % row for row in zip(cons, labels)])
    
    with open(filename, 'wb') as stream:
        stream.write(result.encode('utf-8'))
        
    print('Done!')

## Autoencoder (on chains)

In [11]:
from da.autoencoder import DenoisingAutoencoder

In [12]:
da = DenoisingAutoencoder(n_hidden=20)

In [18]:
X = np.array([list(chain) for chain in all_chains])

In [19]:
da.fit(X)

In [15]:
# changed_X = da.transform_latent_representation(X)

In [20]:
def get_smaller_repr(bchain):
    res = da.transform_latent_representation([bchain])
    return res[0]

In [21]:
get_smaller_repr(chain2bin(u'\u043d\u043e\u0440\u043c\u0430+N+PL(\u041b\u0410\u0440)+POSS_3(\u0421\u042b)+Nom;'))

array([ 0.8309004 ,  0.31024231,  0.4410614 ,  0.676687  ,  0.67247481,
        0.85006472,  0.23955285,  0.65511972,  0.17220817,  0.00230234,
        0.9950252 ,  0.71355422,  0.89788458,  0.92019053,  0.96832388,
        0.97401018,  0.05627823,  0.46019875,  0.90078745,  0.0242656 ])

## KMeans Clustering

#### KMeans with 2 Cluster and without encoder

In [22]:
def get_vector_long(context):
    return chain2bin(context[0][1] if context[0][1] else '') + \
           chain2bin(context[1][1] if context[1][1] else '') + \
           chain2bin(context[3][1] if context[3][1] else '') + \
           chain2bin(context[4][1] if context[4][1] else '')

In [23]:
def get_vector_short(context):
    return get_smaller_repr(chain2bin(context[0][1] if context[0][1] else '')) + \
           get_smaller_repr(chain2bin(context[1][1] if context[1][1] else '')) + \
           get_smaller_repr(chain2bin(context[3][1] if context[3][1] else '')) + \
           get_smaller_repr(chain2bin(context[4][1] if context[4][1] else ''))

In [24]:
def collect_stat_as_table(labels, true_indexes, chains):
    comp = zip(labels, true_indexes)
    clusters = {}
    
    all_sample_count = len(labels)

    for (cluster, chain_index) in comp:
        chain = chains[chain_index]
        if cluster not in clusters:
            clusters[cluster] = {chain: 1}
        else:
            if chain not in clusters[cluster]:
                clusters[cluster][chain] = 1
            else:
                clusters[cluster][chain] += 1
    chs = []
    for value in set(true_indexes):
        chs.append((chains[value], true_indexes.count(value)))
    
    avgd = 0
    for cluster in clusters:
        sample_count = sum([clusters[cluster][chain] for chain in chains if chain in clusters[cluster]])
        dominant = sorted([(chain, clusters[cluster][chain]) for chain in chains if chain in clusters[cluster]], key=lambda x: -x[1])[0]
        clusters[cluster]['3. Most Freq Chain'] = dominant[0]
        clusters[cluster]['1. Samples'] = sample_count
        clusters[cluster]['4. % of Dominant Chain in the Cluster'] = 100. * dominant[1] / sample_count
        clusters[cluster]['2. % of All Samples'] = 100. * sample_count / all_sample_count
        avgd += 100. * dominant[1] / all_sample_count
    
#     avgd = avgd / len(clusters)
    clusters['Sum'] = dict(chs)
    clusters['Sum']['2. % of All Samples'] = 100
    clusters['Sum']['1. Samples'] = all_sample_count
    clusters['Sum']['4. % of Dominant Chain in the Cluster'] = 'Avg: %%%.2f' % avgd
    
    return pd.DataFrame(clusters).transpose()

In [25]:
from sklearn.cluster import KMeans

In [150]:
model2 = KMeans(n_clusters=2)

In [151]:
X = [get_vector_long(context) for context in sentences1]

In [152]:
model2.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [153]:
collect_stat_as_table(model2.labels_, true_indexes1, chains1)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,36,45,әле+CNJ,61.1111,22,14
1,44,55,әле+PART,84.0909,7,37
Sum,80,100,NaN,Avg: %73.75,29,51

In [154]:
save_as(u'әле_2_table1.csv', sentences1, model2.labels_)

Done!

#### KMeans with 2 Cluster and with encoder

In [157]:
model2 = KMeans(n_clusters=2)

In [155]:
Xs = [get_vector_short(context) for context in sentences1]

In [158]:
model2.fit(Xs)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [159]:
collect_stat_as_table(model2.labels_, true_indexes1, chains1)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,50,62.5,әле+PART,74,13,37
1,30,37.5,әле+CNJ,53.3333,16,14
Sum,80,100,NaN,Avg: %66.25,29,51

In [160]:
save_as(u'әле_2_table2.csv', sentences1, model2.labels_)

Done!

#### KMeans with 6 Cluster and without encoder

In [37]:
model6 = KMeans(n_clusters=6)

In [38]:
model6.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=6, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [39]:
collect_stat_as_table(model6.labels_, true_indexes1, chains1)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,4,5,әле+CNJ,75,3,1
1,10,12.5,әле+PART,90,1,9
2,10,12.5,әле+PART,90,1,9
3,40,50,әле+PART,50,20,20
4,4,5,әле+PART,75,1,3
5,12,15,әле+PART,75,3,9
Sum,80,100,NaN,Avg: %66.25,29,51

#### KMeans with 6 Cluster and with encoder

In [40]:
model6 = KMeans(n_clusters=6)

In [41]:
model6.fit(Xs)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=6, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [42]:
collect_stat_as_table(model6.labels_, true_indexes1, chains1)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,14,17.5,әле+PART,50,7,7
1,6,7.5,әле+PART,50,3,3
2,16,20,әле+PART,81.25,3,13
3,17,21.25,әле+CNJ,52.9412,9,8
4,10,12.5,әле+PART,60,4,6
5,17,21.25,әле+PART,82.3529,3,14
Sum,80,100,NaN,Avg: %65.00,29,51

## Autoencoder (on n4gram)

In [43]:
Xc = np.array([get_vector_long(context) for context in all_sentences])

In [44]:
dac = DenoisingAutoencoder(n_hidden=50)

In [45]:
dac.fit(Xc)

In [46]:
def get_smaller_context(bcontext):
    res = dac.transform_latent_representation([bcontext])
    return res[0]

#### KMeans with 6 Cluster and with context encoder

In [47]:
model6c = KMeans(n_clusters=6)

In [49]:
Xsc = [get_smaller_context(get_vector_long(context)) for context in sentences1]

In [50]:
model6c.fit(Xsc)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=6, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [54]:
collect_stat_as_table(model6c.labels_, true_indexes1, chains1)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,10,12.5,әле+PART,70,3,7
1,24,30,әле+CNJ,58.3333,14,10
2,7,8.75,әле+PART,57.1429,3,4
3,9,11.25,әле+PART,88.8889,1,8
4,21,26.25,әле+PART,80.9524,4,17
5,9,11.25,әле+PART,55.5556,4,5
Sum,80,100,NaN,Avg: %68.75,29,51

### TEST

In [161]:
def test(clusters, data, true_indexes, chains, sentences, filename=None):
    mdl = KMeans(n_clusters=clusters)
    mdl.fit(data)
    if filename:
        save_as(filename, sentences, mdl.labels_)
    return collect_stat_as_table(mdl.labels_, true_indexes, chains)

In [56]:
X1 = [get_smaller_context(get_vector_long(context)) for context in sentences1]
X2 = [get_smaller_context(get_vector_long(context)) for context in sentences2]
X3 = [get_smaller_context(get_vector_long(context)) for context in sentences3]

In [209]:
X2s = [get_vector_long(context) for context in sentences2]
X2ec = [get_vector_short(context) for context in sentences2]

In [216]:
X3s = [get_vector_long(context) for context in sentences3]
X3ec = [get_vector_short(context) for context in sentences3]

In [162]:
test(2, X1, true_indexes1, chains1, sentences1, u'әле_2_table3.csv')

Done!

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,48,60,әле+PART,54.1667,22,26
1,32,40,әле+PART,78.125,7,25
Sum,80,100,NaN,Avg: %63.75,29,51

In [57]:
test(3, X1, true_indexes1, chains1)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,31,38.75,әле+PART,80.6452,6,25
1,12,15,әле+PART,91.6667,1,11
2,37,46.25,әле+CNJ,59.4595,22,15
Sum,80,100,NaN,Avg: %72.50,29,51

In [166]:
test(4, X1, true_indexes1, chains1, sentences1, u'әле_4_table4.csv')

Done!

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,17,21.25,әле+PART,52.9412,8,9
1,29,36.25,әле+PART,79.3103,6,23
2,15,18.75,әле+PART,93.3333,1,14
3,19,23.75,әле+CNJ,73.6842,14,5
Sum,80,100,NaN,Avg: %75.00,29,51

In [186]:
test(4, X, true_indexes1, chains1, sentences1, u'әле_4_table6.csv')

Done!

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,7,8.75,әле+PART,100,NaN,7
1,29,36.25,әле+PART,82.7586,5,24
2,13,16.25,әле+PART,76.9231,3,10
3,31,38.75,әле+CNJ,67.7419,21,10
Sum,80,100,NaN,Avg: %77.50,29,51

In [194]:
test(4, Xs, true_indexes1, chains1, sentences1, u'әле_4_table7.csv')

Done!

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,18,22.5,әле+PART,77.7778,4,14
1,15,18.75,әле+PART,53.3333,7,8
2,17,21.25,әле+CNJ,52.9412,9,8
3,30,37.5,әле+PART,70,9,21
Sum,80,100,NaN,Avg: %65.00,29,51

In [59]:
test(5, X1, true_indexes1, chains1)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,32,40,әле+CNJ,65.625,21,11
1,14,17.5,әле+PART,71.4286,4,10
2,12,15,әле+PART,75,3,9
3,12,15,әле+PART,91.6667,1,11
4,10,12.5,әле+PART,100,NaN,10
Sum,80,100,NaN,Avg: %76.25,29,51

In [177]:
test(8, X1, true_indexes1, chains1, sentences1, u'әле_8_table5.csv')

Done!

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,3,3.75,әле+PART,66.6667,1,2
1,7,8.75,әле+PART,71.4286,2,5
2,7,8.75,әле+PART,85.7143,1,6
3,16,20,әле+CNJ,62.5,10,6
4,11,13.75,әле+PART,81.8182,2,9
5,14,17.5,әле+PART,92.8571,1,13
6,12,15,әле+PART,58.3333,5,7
7,10,12.5,әле+CNJ,70,7,3
Sum,80,100,NaN,Avg: %73.75,29,51

In [204]:
test(8, X, true_indexes1, chains1, sentences1, u'әле_8_table8.csv')

Done!

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,9,11.25,әле+CNJ,66.6667,6,3
1,12,15,әле+PART,75,3,9
2,4,5,әле+PART,100,NaN,4
3,5,6.25,әле+PART,80,1,4
4,22,27.5,әле+CNJ,63.6364,14,8
5,16,20,әле+PART,75,4,12
6,7,8.75,әле+PART,100,NaN,7
7,5,6.25,әле+PART,80,1,4
Sum,80,100,NaN,Avg: %75.00,29,51

In [208]:
test(8, Xs, true_indexes1, chains1, sentences1, u'әле_8_table9.csv')

Done!

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,4,5,әле+PART,100,NaN,4
1,11,13.75,әле+PART,90.9091,1,10
2,22,27.5,әле+PART,59.0909,9,13
3,12,15,әле+PART,75,3,9
4,3,3.75,әле+PART,100,NaN,3
5,13,16.25,әле+CNJ,53.8462,7,6
6,13,16.25,әле+CNJ,69.2308,9,4
7,2,2.5,әле+PART,100,NaN,2
Sum,80,100,NaN,Avg: %71.25,29,51

In [61]:
test(10, X1, true_indexes1, chains1)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,10,12.5,әле+CNJ,70,7,3
1,10,12.5,әле+PART,90,1,9
2,12,15,әле+PART,50,6,6
3,5,6.25,әле+PART,60,2,3
4,3,3.75,әле+PART,100,NaN,3
5,4,5,әле+PART,50,2,2
6,19,23.75,әле+PART,57.8947,8,11
7,3,3.75,әле+PART,100,NaN,3
8,7,8.75,әле+PART,71.4286,2,5
9,7,8.75,әле+PART,85.7143,1,6
Sum,80,100,NaN,Avg: %68.75,29,51

### УК

In [213]:
test(2, X2s, true_indexes2, chains2, sentences2, u'ук_2_table12.csv')

Done!

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,ук+PART
0,150,49.0196,ук+PART,100,150
1,156,50.9804,ук+PART,100,156
Sum,306,100,NaN,Avg: %100.00,306

In [214]:
test(4, X2, true_indexes2, chains2, sentences2, u'ук_4_table13.csv')

Done!

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,ук+PART
0,56,18.3007,ук+PART,100,56
1,63,20.5882,ук+PART,100,63
2,114,37.2549,ук+PART,100,114
3,73,23.8562,ук+PART,100,73
Sum,306,100,NaN,Avg: %100.00,306

In [215]:
test(10, X2s, true_indexes2, chains2, sentences2, u'ук_10_table14.csv')

Done!

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,ук+PART
0,54,17.6471,ук+PART,100,54
1,39,12.7451,ук+PART,100,39
2,26,8.49673,ук+PART,100,26
3,29,9.47712,ук+PART,100,29
4,43,14.0523,ук+PART,100,43
5,29,9.47712,ук+PART,100,29
6,35,11.4379,ук+PART,100,35
7,16,5.22876,ук+PART,100,16
8,16,5.22876,ук+PART,100,16
9,19,6.20915,ук+PART,100,19
Sum,306,100,NaN,Avg: %100.00,306

In [64]:
test(4, X2, true_indexes2, chains2)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,ук+PART
0,65,21.2418,ук+PART,100,65
1,104,33.9869,ук+PART,100,104
2,76,24.8366,ук+PART,100,76
3,61,19.9346,ук+PART,100,61
Sum,306,100,NaN,Avg: %100.00,306

In [65]:
test(5, X2, true_indexes2, chains2)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,ук+PART
0,71,23.2026,ук+PART,100,71
1,52,16.9935,ук+PART,100,52
2,49,16.0131,ук+PART,100,49
3,82,26.7974,ук+PART,100,82
4,52,16.9935,ук+PART,100,52
Sum,306,100,NaN,Avg: %100.00,306

In [66]:
test(7, X2, true_indexes2, chains2)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,ук+PART
0,16,5.22876,ук+PART,100,16
1,51,16.6667,ук+PART,100,51
2,44,14.3791,ук+PART,100,44
3,33,10.7843,ук+PART,100,33
4,50,16.3399,ук+PART,100,50
5,57,18.6275,ук+PART,100,57
6,55,17.9739,ук+PART,100,55
Sum,306,100,NaN,Avg: %100.00,306

In [67]:
test(10, X2, true_indexes2, chains2)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,ук+PART
0,30,9.80392,ук+PART,100,30
1,42,13.7255,ук+PART,100,42
2,18,5.88235,ук+PART,100,18
3,30,9.80392,ук+PART,100,30
4,27,8.82353,ук+PART,100,27
5,40,13.0719,ук+PART,100,40
6,24,7.84314,ук+PART,100,24
7,34,11.1111,ук+PART,100,34
8,26,8.49673,ук+PART,100,26
9,35,11.4379,ук+PART,100,35
Sum,306,100,NaN,Avg: %100.00,306

### СОҢ

In [218]:
test(2, X3s, true_indexes3, chains3, sentences3, u'соң_2_table15.csv')

Done!

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,соң+PART,соң+POST
0,26,37.6812,соң+POST,69.2308,8,18
1,43,62.3188,соң+POST,76.7442,10,33
Sum,69,100,NaN,Avg: %73.91,18,51

In [220]:
test(3, X3, true_indexes3, chains3, sentences3, u'соң_3_table16.csv')

Done!

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,соң+PART,соң+POST
0,27,39.1304,соң+POST,74.0741,7,20
1,23,33.3333,соң+POST,86.9565,3,20
2,19,27.5362,соң+POST,57.8947,8,11
Sum,69,100,NaN,Avg: %73.91,18,51

In [69]:
test(4, X3, true_indexes3, chains3)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,соң+PART,соң+POST
0,10,14.4928,соң+PART,60,6,4
1,27,39.1304,соң+POST,85.1852,4,23
2,22,31.8841,соң+POST,72.7273,6,16
3,10,14.4928,соң+POST,80,2,8
Sum,69,100,NaN,Avg: %76.81,18,51

In [70]:
test(6, X3, true_indexes3, chains3)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,соң+PART,соң+POST
0,11,15.942,соң+POST,100,NaN,11
1,10,14.4928,соң+PART,60,6,4
2,14,20.2899,соң+POST,78.5714,3,11
3,11,15.942,соң+POST,72.7273,3,8
4,11,15.942,соң+POST,63.6364,4,7
5,12,17.3913,соң+POST,83.3333,2,10
Sum,69,100,NaN,Avg: %76.81,18,51

In [71]:
test(7, X3, true_indexes3, chains3)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,соң+PART,соң+POST
0,10,14.4928,соң+PART,60,6,4
1,11,15.942,соң+POST,100,NaN,11
2,10,14.4928,соң+POST,90,1,9
3,11,15.942,соң+POST,72.7273,3,8
4,10,14.4928,соң+POST,60,4,6
5,9,13.0435,соң+POST,77.7778,2,7
6,8,11.5942,соң+POST,75,2,6
Sum,69,100,NaN,Avg: %76.81,18,51

In [222]:
test(9, X3s, true_indexes3, chains3, sentences3, u'соң_9_table17.csv')

Done!

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,соң+PART,соң+POST
0,6,8.69565,соң+POST,50,3,3
1,7,10.1449,соң+POST,71.4286,2,5
2,16,23.1884,соң+POST,75,4,12
3,3,4.34783,соң+POST,100,NaN,3
4,5,7.24638,соң+POST,80,1,4
5,8,11.5942,соң+PART,75,6,2
6,5,7.24638,соң+POST,80,1,4
7,5,7.24638,соң+POST,80,1,4
8,14,20.2899,соң+POST,100,NaN,14
Sum,69,100,NaN,Avg: %79.71,18,51

In [73]:
test(12, X3, true_indexes3, chains3)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,соң+PART,соң+POST
0,6,8.69565,соң+POST,100,NaN,6
1,11,15.942,соң+POST,100,NaN,11
2,9,13.0435,соң+PART,66.6667,6,3
3,5,7.24638,соң+PART,80,4,1
4,4,5.7971,соң+POST,75,1,3
5,2,2.89855,соң+POST,50,1,1
6,11,15.942,соң+POST,72.7273,3,8
7,4,5.7971,соң+POST,75,1,3
8,6,8.69565,соң+POST,100,NaN,6
9,1,1.44928,соң+POST,100,NaN,1
10,7,10.1449,соң+POST,71.4286,2,5
11,3,4.34783,соң+POST,100,NaN,3
Sum,69,100,NaN,Avg: %82.61,18,51

### Old tests

In [197]:
test(7)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,13,16.25,әле+CNJ,61.5385,8,5
1,11,13.75,әле+PART,63.6364,4,7
2,6,7.5,әле+PART,83.3333,1,5
3,14,17.5,әле+PART,92.8571,1,13
4,20,25,әле+CNJ,60,12,8
5,6,7.5,әле+PART,83.3333,1,5
6,10,12.5,әле+PART,80,2,8
Sum,80,100,NaN,Avg: %72.50,29,51

In [198]:
test(8)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,6,7.5,әле+PART,100,NaN,6
1,14,17.5,әле+CNJ,57.1429,8,6
2,12,15,әле+PART,91.6667,1,11
3,5,6.25,әле+PART,80,1,4
4,8,10,әле+PART,62.5,3,5
5,7,8.75,әле+PART,100,NaN,7
6,18,22.5,әле+CNJ,72.2222,13,5
7,10,12.5,әле+PART,70,3,7
Sum,80,100,NaN,Avg: %76.25,29,51

In [199]:
test(9)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,10,12.5,әле+PART,80,2,8
1,19,23.75,әле+CNJ,63.1579,12,7
2,13,16.25,әле+PART,92.3077,1,12
3,8,10,әле+CNJ,62.5,5,3
4,4,5,әле+PART,100,NaN,4
5,10,12.5,әле+PART,70,3,7
6,6,7.5,әле+PART,83.3333,1,5
7,6,7.5,әле+CNJ,66.6667,4,2
8,4,5,әле+PART,75,1,3
Sum,80,100,NaN,Avg: %75.00,29,51

In [200]:
test(10)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,7,8.75,әле+CNJ,57.1429,4,3
1,8,10,әле+PART,75,2,6
2,5,6.25,әле+PART,80,1,4
3,10,12.5,әле+CNJ,60,6,4
4,10,12.5,әле+PART,70,3,7
5,12,15,әле+CNJ,66.6667,8,4
6,12,15,әле+PART,91.6667,1,11
7,4,5,әле+PART,75,1,3
8,6,7.5,әле+PART,100,NaN,6
9,6,7.5,әле+PART,50,3,3
Sum,80,100,NaN,Avg: %72.50,29,51

In [201]:
test(11)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,2,2.5,әле+PART,50,1,1
1,22,27.5,әле+CNJ,63.6364,14,8
2,13,16.25,әле+PART,92.3077,1,12
3,12,15,әле+PART,58.3333,5,7
4,5,6.25,әле+PART,80,1,4
5,4,5,әле+PART,75,1,3
6,4,5,әле+PART,100,NaN,4
7,5,6.25,әле+PART,60,2,3
8,2,2.5,әле+PART,100,NaN,2
9,5,6.25,әле+CNJ,80,4,1
10,6,7.5,әле+PART,100,NaN,6
Sum,80,100,NaN,Avg: %75.00,29,51

In [202]:
test(12)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,5,6.25,әле+PART,60,2,3
1,11,13.75,әле+CNJ,54.5455,6,5
2,8,10,әле+PART,100,NaN,8
3,6,7.5,әле+CNJ,66.6667,4,2
4,5,6.25,әле+PART,80,1,4
5,5,6.25,әле+PART,60,2,3
6,11,13.75,әле+CNJ,81.8182,9,2
7,3,3.75,әле+PART,100,NaN,3
8,10,12.5,әле+PART,70,3,7
9,7,8.75,әле+PART,100,NaN,7
10,3,3.75,әле+PART,66.6667,1,2
11,6,7.5,әле+PART,83.3333,1,5
Sum,80,100,NaN,Avg: %76.25,29,51

In [203]:
test(13)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,4,5,әле+PART,75,1,3
1,7,8.75,әле+PART,71.4286,2,5
2,7,8.75,әле+PART,85.7143,1,6
3,2,2.5,әле+PART,50,1,1
4,4,5,әле+PART,100,NaN,4
5,14,17.5,әле+CNJ,78.5714,11,3
6,3,3.75,әле+PART,100,NaN,3
7,3,3.75,әле+PART,66.6667,1,2
8,8,10,әле+PART,75,2,6
9,5,6.25,әле+PART,60,2,3
10,8,10,әле+PART,87.5,1,7
11,4,5,әле+PART,100,NaN,4
12,11,13.75,әле+CNJ,63.6364,7,4
Sum,80,100,NaN,Avg: %77.50,29,51

In [204]:
test(14)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,10,12.5,әле+PART,70,3,7
1,13,16.25,әле+PART,92.3077,1,12
2,6,7.5,әле+CNJ,66.6667,4,2
3,5,6.25,әле+PART,80,1,4
4,15,18.75,әле+CNJ,66.6667,10,5
5,6,7.5,әле+PART,100,NaN,6
6,2,2.5,әле+PART,100,NaN,2
7,6,7.5,әле+CNJ,83.3333,5,1
8,3,3.75,әле+CNJ,66.6667,2,1
9,4,5,әле+PART,100,NaN,4
10,4,5,әле+PART,75,1,3
11,1,1.25,әле+PART,100,NaN,1
12,4,5,әле+PART,50,2,2
13,1,1.25,әле+PART,100,NaN,1
Sum,80,100,NaN,Avg: %78.75,29,51

In [205]:
test(15)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,1,1.25,әле+PART,100,NaN,1
1,7,8.75,әле+PART,71.4286,2,5
2,6,7.5,әле+PART,100,NaN,6
3,15,18.75,әле+CNJ,73.3333,11,4
4,8,10,әле+PART,75,2,6
5,8,10,әле+CNJ,62.5,5,3
6,8,10,әле+PART,87.5,1,7
7,3,3.75,әле+PART,66.6667,1,2
8,1,1.25,әле+PART,100,NaN,1
9,3,3.75,әле+PART,66.6667,1,2
10,5,6.25,әле+CNJ,80,4,1
11,1,1.25,әле+PART,100,NaN,1
12,5,6.25,әле+PART,80,1,4
13,6,7.5,әле+PART,100,NaN,6
14,3,3.75,әле+PART,66.6667,1,2
Sum,80,100,NaN,Avg: %78.75,29,51

# С расширением данных

In [81]:
sent1 = get_contexts(ALL_TEXTS, [u'әле'])
len(sent1)

5707

In [99]:
sent1[0]

((u'\u043f\u0440\u043e\u0431\u043b\u0435\u043c\u0430\u0441\u044b',
  u'\u043f\u0440\u043e\u0431\u043b\u0435\u043c\u0430+N+Sg+POSS_3(\u0421\u042b)+Nom;'),
 (u'\u0445\u0430\u043c\u0430\u043d', u'\u0445\u0430\u043c\u0430\u043d+Adv;'),
 (u'\u04d9\u043b\u0435', u'\u04d9\u043b\u0435+PART'),
 (u'\u043a\u0438\u0441\u043a\u0435\u043d',
  u'\u043a\u0438\u0441\u043a\u0435\u043d+Adj;'),
 (u'\u0431\u0443\u043b\u044b\u043f',
  u'\u0431\u0443\u043b+V+ADVV_ACC(\u042b\u043f);'))

In [100]:
sent = [(r1, r2, w, l1, l2) for r1, r2, w, l1, l2 in sent1 if len(w[1].split(';')) == 1]

In [102]:
len(sent)

3386

In [112]:
true_1, ch1 = get_disamed_indexes(sent)

In [104]:
X1r = [get_smaller_context(get_vector_long(context)) for context in sent]

In [113]:
test(2, X1r, true_1, ch1)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,1119,33.0478,әле+PART,68.7221,350,769
1,2267,66.9522,әле+PART,69.3869,694,1573
Sum,3386,100,NaN,Avg: %69.17,1044,2342

In [114]:
test(3, X1r, true_1, ch1)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,1511,44.6249,әле+PART,69.4242,462,1049
1,789,23.3018,әле+PART,69.5817,240,549
2,1086,32.0732,әле+PART,68.5083,342,744
Sum,3386,100,NaN,Avg: %69.17,1044,2342

In [115]:
test(4, X1r, true_1, ch1)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,1064,31.4235,әле+PART,68.797,332,732
1,667,19.6988,әле+PART,70.1649,199,468
2,671,19.8169,әле+PART,71.8331,189,482
3,984,29.0608,әле+PART,67.0732,324,660
Sum,3386,100,NaN,Avg: %69.17,1044,2342

In [116]:
test(5, X1r, true_1, ch1)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,452,13.3491,әле+PART,68.8053,141,311
1,649,19.1672,әле+PART,69.7997,196,453
2,893,26.3733,әле+PART,67.3012,292,601
3,673,19.876,әле+PART,71.9168,189,484
4,719,21.2345,әле+PART,68.5675,226,493
Sum,3386,100,NaN,Avg: %69.17,1044,2342

In [117]:
test(6, X1r, true_1, ch1)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,707,20.8801,әле+PART,67.3267,231,476
1,336,9.92321,әле+PART,71.4286,96,240
2,596,17.6019,әле+PART,69.9664,179,417
3,584,17.2475,әле+PART,71.0616,169,415
4,712,21.0278,әле+PART,68.118,227,485
5,451,13.3196,әле+PART,68.5144,142,309
Sum,3386,100,NaN,Avg: %69.17,1044,2342

In [118]:
test(8, X1r, true_1, ch1)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,321,9.48021,әле+PART,72.5857,88,233
1,156,4.60721,әле+PART,66.0256,53,103
2,584,17.2475,әле+PART,67.9795,187,397
3,472,13.9398,әле+PART,71.1864,136,336
4,339,10.0118,әле+PART,73.4513,90,249
5,396,11.6952,әле+PART,68.1818,126,270
6,468,13.8216,әле+PART,71.5812,133,335
7,650,19.1967,әле+PART,64.4615,231,419
Sum,3386,100,NaN,Avg: %69.17,1044,2342

In [119]:
test(10, X1r, true_1, ch1)

,1. Samples,2. % of All Samples,3. Most Freq Chain,4. % of Dominant Chain in the Cluster,әле+CNJ,әле+PART
0,153,4.51861,әле+PART,66.0131,52,101
1,321,9.48021,әле+PART,69.7819,97,224
2,414,12.2268,әле+PART,68.599,130,284
3,313,9.24395,әле+PART,64.2173,112,201
4,395,11.6657,әле+PART,69.6203,120,275
5,271,8.00354,әле+PART,73.0627,73,198
6,366,10.8092,әле+PART,69.9454,110,256
7,437,12.9061,әле+PART,70.4805,129,308
8,395,11.6657,әле+PART,68.1013,126,269
9,321,9.48021,әле+PART,70.405,95,226
Sum,3386,100,NaN,Avg: %69.17,1044,2342